version: '3.8'
services:
  app:
    image: janwodniak/reactive-crud-native-amd64:latest
    #    image: janwodniak/reactive-crud-native-arm64:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network


networks:
  app-network:
    driver: bridge