spring:
  main:
    web-application-type: reactive
  r2dbc:
    url: 'r2dbc:postgresql://postgresql:5432/notes'
    username: 'postgres'
    password: 'postgres'
  liquibase:
    enabled: true
    url: 'jdbc:postgresql://postgresql:5432/notes'
    user: 'postgres'
    password: 'postgres'
    change-log: 'classpath:/db/liquibase-changelog.xml'
  sql:
    init:
      mode: never

data:
  initializer:
    enabled: true